spring:
  application:
    name: mcp-slack-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

server:
  port: ${SERVER_PORT:8096}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Slack 설정 (실제 값은 환경변수나 별도 설정 파일에서 설정)
slack:
  bot-token: ${SLACK_BOT_TOKEN:your-bot-token-here}
  app-token: ${SLACK_APP_TOKEN:your-app-token-here}
  signing-secret: ${SLACK_SIGNING_SECRET:your-signing-secret-here}
  default-channel: ${SLACK_DEFAULT_CHANNEL:general}
  socket-mode:
    enabled: ${SLACK_SOCKET_MODE_ENABLED:true}

# Q&A 봇 설정
qa-bot:
  enabled: ${QA_BOT_ENABLED:true}
  matching:
    similarity-threshold: ${QA_BOT_SIMILARITY_THRESHOLD:0.3}

# Google Cloud 설정 (선택사항)
google:
  cloud:
    project: ${GOOGLE_CLOUD_PROJECT:your-project-id}
    location: ${GOOGLE_CLOUD_LOCATION:asia-northeast1}

# 로깅 설정
logging:
  level:
    com.monkeys.slack: ${LOG_LEVEL:INFO}
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"