server:
  port: 8092

spring:
  application:
    name: weather-mcp-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key}
    mcp:
      server:
        enabled: true
        name: weather-mcp-server
        version: 1.0.0
        type: SYNC
        description: "Weather information service using OpenWeatherMap API"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: true

weather:
  api:
    key: ${WEATHER_API_KEY:dummy-key}

shared:
  http-client:
    connect-timeout-seconds: 10
    read-timeout-seconds: 30
    write-timeout-seconds: 30
    max-idle-connections: 5
    keep-alive-duration-minutes: 5
    retry-on-connection-failure: true
    user-agent: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: health,info,mcp,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        weather.api.request: true

logging:
  level:
    com.monkeys.weather: DEBUG
    org.springframework.ai: INFO