server:
  port: 8082

spring:
  application:
    name: github-mcp-server
  ai:
    openai:
      api-key: dummy-key

github:
  token: ${GITHUB_TOKEN:dummy-token}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.monkeys.github: DEBUG
    org.springframework.ai: INFO