server:
  port: 8093

spring:
  application:
    name: news-mcp-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key}
    mcp:
      server:
        enabled: true
        name: news-mcp-server
        version: 1.0.0
        type: SYNC
        description: "News search and headlines service using NewsAPI"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: true

news:
  api:
    key: ${NEWS_API_KEY:dummy-key}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mcp
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.monkeys.news: DEBUG
    org.springframework.ai: INFO