server:
  port: 8094

spring:
  application:
    name: translate-mcp-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key}
    mcp:
      server:
        enabled: true
        name: translate-mcp-server
        version: 1.0.0
        type: SYNC
        description: "Multi-language translation service"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,mcp
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.monkeys.translate: DEBUG
    org.springframework.ai: INFO