server:
  port: 8094

spring:
  application:
    name: gmail-mcp-server
  ai:
    openai:
      api-key: dummy-key

gmail:
  client-id: ${GMAIL_CLIENT_ID:dummy-client-id}
  client-secret: ${GMAIL_CLIENT_SECRET:dummy-client-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.monkeys.gmail: DEBUG
    org.springframework.ai: INFO